export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/';
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const URL_IMG = 'https://image.tmdb.org/t/p/';
export const API_KEY = '?api_key=a2df3d1a7611194432bbdf1fc80540f2';
export const API_KEY_ALT = '&api_key=a2df3d1a7611194432bbdf1fc80540f2';
export const IMG_BACKGROUND = 'original'
export const IMG_LARGE = 'w500/';
export const IMG_XSMALL = 'w45/';
export const VIDEOS = '/videos';
export const LANGUAGE_EN = '&language=en-US&page=1';
export const POPULAR = 'popular';
export const UPCOMING = 'upcoming';